server.port=8080

paypal.client-id=AbvGRi6K6MdJkoxDEh08IbYorC_Qtx4tAt5WGqcIw2WAaoKHJQkXGccAdWnyDosVxsDtLBGU-0TJI0BO
paypal.secret=EC6_Gh8brC8Rrl3g3Xi83rt6hJ6FW5RaehdWh14FuNUICIVTl0AHpxc53rRjIPvXb5gCFanE-nJjwa8g
paypal.base-url=https://api-m.sandbox.paypal.com

spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


###https://www.sandbox.paypal.com/checkoutnow?token=7RV026579C140515W